version: '3.7'
services:
  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_USER=opa-user
      - MYSQL_PASSWORD=opa-user
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=opa_web
    ports:
      - 4000:3306

networks:
  opa_network:
    driver: bridge
