version: '3.7'
services:
  opa_api_backend:
    build:
      context: .
    volumes:
      - '.:/app'
    entrypoint: ./.docker/opa_init_script.sh
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - opa_network

  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_USER=opa-user
      - MYSQL_PASSWORD=opa-user
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=opa_web
    ports:
      - 4000:3306

networks:
  opa_network:
    driver: bridge
